services:
  bizserver:
    build:
      context: ./bizserver
      dockerfile: Dockerfile
    ports:
      - 5062:5062
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=biz_database
    # network_mode: "host"
  postgres_db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=biz_database
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # expose:
    #   - "5432"
