// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: auth_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqPqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce     string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MessageId int64  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *ReqPqRequest) Reset() {
	*x = ReqPqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPqRequest) ProtoMessage() {}

func (x *ReqPqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPqRequest.ProtoReflect.Descriptor instead.
func (*ReqPqRequest) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPqRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ReqPqRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ReqPqReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *RequestBasicInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	P    int64             `protobuf:"varint,2,opt,name=p,proto3" json:"p,omitempty"`
	G    int64             `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
}

func (x *ReqPqReply) Reset() {
	*x = ReqPqReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPqReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPqReply) ProtoMessage() {}

func (x *ReqPqReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPqReply.ProtoReflect.Descriptor instead.
func (*ReqPqReply) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPqReply) GetInfo() *RequestBasicInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ReqPqReply) GetP() int64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *ReqPqReply) GetG() int64 {
	if x != nil {
		return x.G
	}
	return 0
}

type Req_DHParamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *RequestBasicInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	A    int64             `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *Req_DHParamsRequest) Reset() {
	*x = Req_DHParamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_DHParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_DHParamsRequest) ProtoMessage() {}

func (x *Req_DHParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_DHParamsRequest.ProtoReflect.Descriptor instead.
func (*Req_DHParamsRequest) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{2}
}

func (x *Req_DHParamsRequest) GetInfo() *RequestBasicInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Req_DHParamsRequest) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

type Req_DHParamsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *RequestBasicInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	B    int64             `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Req_DHParamsReply) Reset() {
	*x = Req_DHParamsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_DHParamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_DHParamsReply) ProtoMessage() {}

func (x *Req_DHParamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_DHParamsReply.ProtoReflect.Descriptor instead.
func (*Req_DHParamsReply) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{3}
}

func (x *Req_DHParamsReply) GetInfo() *RequestBasicInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Req_DHParamsReply) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type RequestBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce       string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce string `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId   int64  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *RequestBasicInfo) Reset() {
	*x = RequestBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBasicInfo) ProtoMessage() {}

func (x *RequestBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBasicInfo.ProtoReflect.Descriptor instead.
func (*RequestBasicInfo) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{4}
}

func (x *RequestBasicInfo) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *RequestBasicInfo) GetServerNonce() string {
	if x != nil {
		return x.ServerNonce
	}
	return ""
}

func (x *RequestBasicInfo) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_auth_server_proto protoreflect.FileDescriptor

var file_auth_server_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x71, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x0b, 0x72, 0x65, 0x71,
	0x5f, 0x70, 0x71, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x70, 0x12,
	0x0c, 0x0a, 0x01, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x67, 0x22, 0x4d, 0x0a,
	0x14, 0x72, 0x65, 0x71, 0x5f, 0x44, 0x48, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x0c,
	0x0a, 0x01, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x22, 0x4b, 0x0a, 0x12,
	0x72, 0x65, 0x71, 0x5f, 0x44, 0x48, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x0c, 0x0a, 0x01, 0x62,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x22, 0x6c, 0x0a, 0x12, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x32, 0x81, 0x01, 0x0a, 0x16, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x71, 0x12, 0x0e, 0x2e, 0x72,
	0x65, 0x71, 0x5f, 0x70, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x72,
	0x65, 0x71, 0x5f, 0x70, 0x71, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d,
	0x72, 0x65, 0x71, 0x5f, 0x44, 0x48, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x15, 0x2e,
	0x72, 0x65, 0x71, 0x5f, 0x44, 0x48, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x71, 0x5f, 0x44, 0x48, 0x5f, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_server_proto_rawDescOnce sync.Once
	file_auth_server_proto_rawDescData = file_auth_server_proto_rawDesc
)

func file_auth_server_proto_rawDescGZIP() []byte {
	file_auth_server_proto_rawDescOnce.Do(func() {
		file_auth_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_server_proto_rawDescData)
	})
	return file_auth_server_proto_rawDescData
}

var file_auth_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_auth_server_proto_goTypes = []interface{}{
	(*ReqPqRequest)(nil),        // 0: req_pqRequest
	(*ReqPqReply)(nil),          // 1: req_pqReply
	(*Req_DHParamsRequest)(nil), // 2: req_DH_paramsRequest
	(*Req_DHParamsReply)(nil),   // 3: req_DH_paramsReply
	(*RequestBasicInfo)(nil),    // 4: request_basic_info
}
var file_auth_server_proto_depIdxs = []int32{
	4, // 0: req_pqReply.info:type_name -> request_basic_info
	4, // 1: req_DH_paramsRequest.info:type_name -> request_basic_info
	4, // 2: req_DH_paramsReply.info:type_name -> request_basic_info
	0, // 3: authentication_service.req_pq:input_type -> req_pqRequest
	2, // 4: authentication_service.req_DH_params:input_type -> req_DH_paramsRequest
	1, // 5: authentication_service.req_pq:output_type -> req_pqReply
	3, // 6: authentication_service.req_DH_params:output_type -> req_DH_paramsReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_server_proto_init() }
func file_auth_server_proto_init() {
	if File_auth_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPqReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_DHParamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_DHParamsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_server_proto_goTypes,
		DependencyIndexes: file_auth_server_proto_depIdxs,
		MessageInfos:      file_auth_server_proto_msgTypes,
	}.Build()
	File_auth_server_proto = out.File
	file_auth_server_proto_rawDesc = nil
	file_auth_server_proto_goTypes = nil
	file_auth_server_proto_depIdxs = nil
}
